// Generated by CoffeeScript 1.6.2
(function() {
  uLecture.controller('lectureController', function($scope, $location, $routeParams, lectureModel) {
    return $scope.lectures = lectureModel.lectures(1);
  });

  uLecture.controller('commentController', function($scope, $location, $routeParams, $resource, lectureModel) {
    var lecture, name;

    lecture = $routeParams.lectureId;
    name = $routeParams.lectureName;
    $scope.isTeacher = function() {
      return true;
    };
    $scope.name = name;
    $scope.comments = lectureModel.getComments(name);
    return $scope.addComment = function() {
      $scope.comments = lectureModel.addComment(lecture, $scope.comment);
      name = name + 'f';
      return $location.path('/comments/' + lecture + '/' + name);
    };
  });

  uLecture.controller('addLectureController', function($scope, $location, $routeParams, lectureModel) {
    return $scope.addLecture = function() {
      lectureModel.addLecture({
        name: $scope.name,
        url: $scope.url
      });
      if ($scope.more) {
        return $location.path('/add/');
      } else {
        return $location.path('/lectures/');
      }
    };
  });

}).call(this);
