// Generated by CoffeeScript 1.6.2
uLecture.controller('lectureController', function($scope, $location, $routeParams, lectureModel) {
  $scope.lectures = lectureModel.lectures(1);
  $scope.addLecture = function() {
    lectureModel.addLecture({
      url: $routeParams.url,
      name: $routeParams.name
    });
    return $location.path('/manageLectures/');
  };
  return 1;
});

uLecture.controller('commentController', function($scope, $location, $routeParams, $resource, lectureModel) {
  var lecture, name;

  lecture = $routeParams.lectureId;
  name = $routeParams.lectureName;
  $scope.isTeacher = function() {
    return true;
  };
  $scope.name = name;
  $scope.comments = lectureModel.commentCRUD(lecture);
  $scope.addComment = function() {
    $scope.comments = lectureModel.addComment(lecture, $scope.comment);
    return $location.path('/comments/' + lecture + '/' + name);
  };
  return 1;
});

/*
uLecture.controller 'addLectureController',
    ($scope, $location, $routeParams,lectureModel) ->
       lecture = $routeParams.lectureId
       lectureModel.comments lecture, (l) -> $scope.comments = l
*/

