// Generated by CoffeeScript 1.6.2
uLecture.controller('lectureController', function($scope, $location, $routeParams, lectureModel) {
  $scope.lectures = lectureModel.lectures(1);
  return $scope.play = function(vidjo) {
    return $scope.vidjo = vidjo.replace(/.*=/, '');
  };
});

uLecture.controller('commentController', function($scope, $location, $routeParams, $resource, lectureModel) {
  var lecture, name;

  lecture = $routeParams.lectureId;
  name = $routeParams.lectureName;
  $scope.isTeacher = function() {
    return true;
  };
  $scope.name = name;
  $scope.comments = lectureModel.getComments(name);
  return $scope.addComment = function() {
    $scope.comments = lectureModel.addComment(name, $scope.comment);
    return $location.path('/comments/' + lecture + '/' + name);
  };
});

uLecture.controller('addLectureController', function($scope, $location, $routeParams, lectureModel) {
  return $scope.addLecture = function() {
    lectureModel.addLecture({
      name: $scope.name,
      url: $scope.url
    });
    if ($scope.more) {
      return $location.path('/add/');
    } else {
      return $location.path('/lectures/');
    }
  };
});
